### ISSUE TITLE
nginx部署后报错:500 Internal Server Error

### ISSUE THREAD

**Issue by liukuan97** [tsxcw/mtab#1]
使用按教程使用nginx部署后报错：不太明白为什么会报这个错误
500 Internal Server Error
nginx/1.18.0 (Ubuntu)

**Comment by tsxcw** [comment]
1、需要检查一下程序目录权限是否为755，
2、检查Nginx的伪静态是否配置
3、检查一下数据库的配置是否正确（一般这个问题比较多）。以及mysql数据库的版本是否大于5.7.4
以上没问题可以联系我协助你处理。

**Comment by liukuan97** [comment]
除了php我使用了更高版本8.1外，应该没有其它问题，我使用php7.4的环境后正常进入install界面，但是当我输入信息安装完成后点击进入首页后还是处于安装界面，此时我的权限设置是775
![image](https://github.com/tsxcw/mtab/assets/115337498/a99a0dfb-cb6e-4ae4-986f-2b97a80db5cb)
我怀疑是安装失败，更改权限为777后，再安装后点击进入首页后出现以下画面：
![image](https://github.com/tsxcw/mtab/assets/115337498/d581d65a-9906-42fa-a770-4709856ef3f9)

**Comment by tsxcw** [comment]
那问题一般就出现在数据库问题，并非数据库账号密码问题，您可以能创建了一个数据库，但是数据库的用户名和数据库名在安装的时候，数据库名称没有填写为和你创建的数据库名一样。导致程序创建数据库失败了。解决方法，可以试着使用root用户和密码来安装程序。

**Comment by tsxcw** [comment]
如果问题还没有解决可以直接联系我直接为你远程或者协助来安装，并且收集一些错误信息，以便完善安装流程。我的QQ:1756328925
