### ISSUE TITLE
突然访问不了

### ISSUE THREAD

**Issue by airpro2** [tsxcw/mtab#17]
![268acf8e8caec3c8b3993de7f72eb632](https://github.com/user-attachments/assets/4114f79a-747b-4031-8277-bcfc090ed0c6)

**Comment by airpro2** [comment]
用docker部署的，重启容器后还是这样

**Comment by tsxcw** [comment]
这个问题是数据库的地址不正确，因为部署的时候那可能数据库ip填的是容器的那个ip，导致容器重启后ip变动，请改为内网的ip。或者网关的ip，或者通过容器名连接数据库

**Comment by tsxcw** [comment]
如还有其他问题可以加入qq群，来寻找帮助694155153

**Comment by airpro2** [comment]
就是通过容器名连接数据库，用了大半个月没问题，不知道怎么突然就访问不了

**Comment by tsxcw** [comment]
如果是通过容器名，请检查数据库是都启动正常运行，然后检查书签容器和数据库容器是否在一个网络的网关下
