### ISSUE TITLE
如何找回管理账号密码？如何重新安装？

### ISSUE THREAD

**Issue by bkzy333** [tsxcw/mtab#21]
已经在网页安装页面填写了管理员邮箱和密码，可以正常创建数据库，但是在网页前端页面登录时提示“账号不存在”
请问如何找回管理员账号密码？或者要删除哪个文件可以重新安装数据库？

![2024-08-31_164930](https://github.com/user-attachments/assets/8f02af03-5a9a-4d8a-9e0e-175d7f82adfc)
![2024-08-31_164950](https://github.com/user-attachments/assets/8f680aac-7b15-4d71-a754-84723b833b7c)
![2024-08-31_164848](https://github.com/user-attachments/assets/45d83779-aaa4-4795-9d5c-252d28d387d2)
![2024-08-31_165131](https://github.com/user-attachments/assets/47d04b37-f54f-4cb0-8bf1-fd8889810895)

**Comment by bkzy333** [comment]
在网页安装过程中出现504错误，并且有下图的报错，但是刷新页面后可以重新键入mtab，不知道具体是什么问题。
![2024-08-31_170441](https://github.com/user-attachments/assets/481dd029-b9c5-48c0-a68b-2320fae3ef47)

**Comment by tsxcw** [comment]
我看到你的数据表的结构不全，应该用的是mariadb的低版本，不支持一些字段的类型，导致写入失败，
，如果你是要重新安装请删除public/目录下的installed.lock文件

**Comment by tsxcw** [comment]
如果是正常使用的时候密码忘了，可以使用终端进入程序根目录执行php think  repass -u 你的用户名 -p 新的密码 进行重新设置，用户名是你的邮箱注册账号，或者安装时的账号

**Comment by bkzy333** [comment]
> 如果是正常使用的时候密码忘了，可以使用终端进入程序根目录执行php think repass -u 你的用户名 -p 新的密码 进行重新设置，用户名是你的邮箱注册账号，或者安装时的账号

感谢回复，已经重新安装升级mariadb。感谢提供重新安装的方法
