### ISSUE TITLE
新功能请求：希望可以隐藏时间区域

### ISSUE THREAD

**Issue by DaisyHunter** [tsxcw/mtab#30]
时间区域的时钟跳动与时间信息有时会干扰注意力，希望可以提供隐藏时钟的设置。
![image](https://github.com/user-attachments/assets/82926476-adfe-4a17-bb40-3c4b62388850)

**Comment by tsxcw** [comment]
在个人中心->时间里面可以关掉的，包括搜索框在最新版也是支持的。
![image](https://github.com/user-attachments/assets/59881d02-bc56-4e52-9054-0f7b3c603f1c)

**Comment by DaisyHunter** [comment]
> 在个人中心->时间里面可以关掉的，包括搜索框在最新版也是支持的。 ![image](https://private-user-images.githubusercontent.com/51120332/385275926-59881d02-bc56-4e52-9054-0f7b3c603f1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTQwNTQsIm5iZiI6MTczMTQxMzc1NCwicGF0aCI6Ii81MTEyMDMzMi8zODUyNzU5MjYtNTk4ODFkMDItYmM1Ni00ZTUyLTkwNTQtMGY3YjNjNjAzZjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEyMTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDY0OTA5Mzc2NDEwZGIyY2E0ZTdhZDJiODliN2I4NDlkMDM1ZGEyMTZiNmU2MmYxMDg3ZGY2YjdiZDlhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MBbkSuSFaiowSRv7A52Wx6yzJSHleQUsdvAVefAr3gk)

好的，谢谢。
